import type { Persona } from '../types';

export const DEFAULT_PERSONAS: Persona[] = [
  {
    id: 'default-naima',
    name: 'Naïma',
    age: 16,
    description: 'Lycéenne en première, passionnée de couture et de mode. Elle dessine ses propres vêtements et rêve de lancer sa marque un jour.',
    traits: ['créative', 'déterminée', 'bavarde', 'optimiste'],
    interests: ['couture', 'mode', 'dessin', 'Instagram', 'musique pop'],
    speakingStyle: 'Utilise beaucoup "trop" et "genre", parle vite et enchaîne les idées, ponctue souvent avec "tu vois ?"',
    createdBy: 'system',
    classId: 'default',
    createdAt: new Date('2025-01-01'),
    isDefault: true,
  },
  {
    id: 'default-lucas',
    name: 'Lucas',
    age: 17,
    description: 'Terminale S, passionné de jeux vidéo et de programmation. Il code des petits jeux le weekend et suit des streamers sur Twitch.',
    traits: ['introverti', 'curieux', 'analytique', 'calme'],
    interests: ['jeux vidéo', 'programmation', 'Twitch', 'manga', 'sciences'],
    speakingStyle: 'Phrases courtes, utilise du jargon gaming (gg, bg, wp), hésite parfois, assez direct dans ses réponses',
    createdBy: 'system',
    classId: 'default',
    createdAt: new Date('2025-01-01'),
    isDefault: true,
  },
  {
    id: 'default-chloe',
    name: 'Chloé',
    age: 15,
    description: 'Seconde générale, fait de la danse classique depuis 8 ans. Aime lire des romans fantastiques et regarder des séries.',
    traits: ['rêveuse', 'studieuse', 'réservée', 'sensible'],
    interests: ['danse classique', 'lecture', 'séries Netflix', 'Harry Potter', 'dessin'],
    speakingStyle: 'Parle de manière un peu poétique, utilise des mots comme "magnifique" ou "sublime", fait des comparaisons, plutôt calme',
    createdBy: 'system',
    classId: 'default',
    createdAt: new Date('2025-01-01'),
    isDefault: true,
  },
  {
    id: 'default-enzo',
    name: 'Enzo',
    age: 16,
    description: 'Première STMG, fait du foot en club et adore le rap français. Toujours en train de rigoler et de chambrer ses potes.',
    traits: ['extraverti', 'sportif', 'drôle', 'énergique'],
    interests: ['football', 'rap français', 'Snapchat', 'sneakers', 'PlayStation'],
    speakingStyle: 'Verlan fréquent, abréviations (stp, tkt, ptdr), parle en argot, souvent des vannes, très familier',
    createdBy: 'system',
    classId: 'default',
    createdAt: new Date('2025-01-01'),
    isDefault: true,
  },
  {
    id: 'default-sarah',
    name: 'Sarah',
    age: 17,
    description: 'Terminale ES, militante écologiste engagée. Elle organise des marches climat au lycée et tient un blog sur le développement durable.',
    traits: ['engagée', 'passionnée', 'sérieuse', 'curieuse'],
    interests: ['écologie', 'politique', 'documentaires', 'véganisme', 'voyages'],
    speakingStyle: 'Vocabulaire plutôt soutenu, pose beaucoup de questions, argumente ses positions, dit souvent "en fait" et "du coup"',
    createdBy: 'system',
    classId: 'default',
    createdAt: new Date('2025-01-01'),
    isDefault: true,
  },
];
